#!/usr/bin/env node
// Packages the app-wide kits (motion-kit/, message-kit/) as Static Application Files.
//
//   node tools/build-kit.mjs            write motion-kit/dist/
//   node tools/build-kit.mjs --check    fail if motion-kit/dist/ is stale (CI)
//
// Outputs:
//   dist/apexlang/shared-components/static-files/amc-motion-kit/*   file content (APEX 26.1+)
//   dist/apexlang/static-files.snippet.apx                          entries for static-files.apx
//   dist/apexlang/application.snippet.apx                           css/javaScript blocks for application.apx
//   dist/legacy/install_amc_motion_kit.sql                          Static Application Files (APEX 23.1+)

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { LEGACY_BASELINE } from "./lib/tokens.mjs";

const SKILL_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
// App-wide kits packaged as Static Application Files (each is optional; only existing kits build).
const KITS = [
  { dir: "motion-kit", folder: "amc-motion-kit", title: "Motion Kit", files: ["amc-motion-kit.css", "amc-motion-kit.js"] },
  { dir: "message-kit", folder: "amc-message-kit", title: "Message Kit", files: ["amc-message-kit.css", "amc-message-kit.js"] },
  { dir: "theme-kit", folder: "amc-theme-kit", title: "Theme Kit", files: ["amc-theme-kit.css", "amc-theme-kit.js"] }
].filter((k) => fs.existsSync(path.join(SKILL_ROOT, k.dir, k.files[0])));
const check = process.argv.includes("--check");
const outputs = new Map();
const makeId = (s) => {
  const h = crypto.createHash("sha256").update(s).digest();
  return (h.readBigUInt64BE(0) % 900000000000000000n) + 100000000000000000n;
};
const q = (s) => `'${String(s).replace(/'/g, "''")}'`;

for (const kitDef of KITS) buildKit(kitDef);

function buildKit({ dir, folder: FOLDER, title, files }) {
const KIT = path.join(SKILL_ROOT, dir);
const DIST = path.join(KIT, "dist");
const FILES = files.map((name) => ({ name, mime: name.endsWith(".css") ? "text/css" : "application/javascript" }));
const cssName = files.find((f) => f.endsWith(".css"));

// Minimal rules for the kit (it targets Universal Theme classes on purpose, so the
// component validator's amc-only selector rule does not apply here).
const css = fs.readFileSync(path.join(KIT, cssName), "utf8");
const errors = [];
css.split("\n").forEach((line, i) => {
  const code = line.replace(/\/\*.*?\*\//g, "");
  if (/#[0-9a-fA-F]{3,8}\b|rgba?\(|hsla?\(/.test(code) && !/var\(/.test(code)) {
    errors.push(`${cssName} line ${i + 1}: literal color outside a var() fallback`);
  }
  if (/transition\s*:\s*all\b/.test(code)) errors.push(`${cssName} line ${i + 1}: transition: all`);
});
if (!/@media \(prefers-reduced-motion: no-preference\)/.test(css)) {
  errors.push(`${cssName}: motion must sit inside @media (prefers-reduced-motion: no-preference)`);
}
if (errors.length) {
  errors.forEach((e) => console.error(`error ${e}`));
  return process.exit(1);
}


const urls = { css: [], js: [] };
const staticEntries = [];
const sql = [
  "prompt --application/set_environment",
  "set define off verify off feedback off",
  "whenever sqlerror exit sql.sqlcode rollback",
  "--------------------------------------------------------------------------------",
  `-- APEX Modern Components: ${title} as Static Application Files.`,
  `-- Stamped for APEX ${LEGACY_BASELINE.release}; imports into every later release.`,
  "-- Generated by skills/apex-modern-components/tools/build-kit.mjs. Do not edit by hand.",
  "--",
  "-- Import with App Builder > (your app) > Shared Components > Export/Import > Import, file type",
  "-- Application, Page or Component Export; or run in SQLcl after apex_application_install.set_*.",
  `-- Then add the File URLs listed in ${dir}/README.md (User Interface attributes).`,
  "--------------------------------------------------------------------------------",
  "begin",
  "wwv_flow_imp.import_begin (",
  ` p_version_yyyy_mm_dd=>${q(LEGACY_BASELINE.versionDate)}`,
  `,p_release=>${q(LEGACY_BASELINE.release)}`,
  ",p_default_workspace_id=>apex_application_install.get_workspace_id",
  ",p_default_application_id=>apex_application_install.get_application_id",
  ",p_default_id_offset=>apex_application_install.get_offset",
  ",p_default_owner=>apex_application_install.get_schema",
  ");",
  "end;",
  "/"
];

for (const f of FILES) {
  const content = fs.readFileSync(path.join(KIT, f.name));
  const published = `${FOLDER}/${f.name}`;
  outputs.set(path.join(DIST, "apexlang", "shared-components", "static-files", FOLDER, f.name), content);
  staticEntries.push(`file "${published}" (`, `    mimeType: ${f.mime}`, "    charSet: utf-8", ")", "");
  (f.name.endsWith(".css") ? urls.css : urls.js).push(`#APP_FILES#${published}`);
  const hex = content.toString("hex").toUpperCase();
  sql.push(`prompt --application/shared_components/files/${published.replace(/[^a-z0-9]+/gi, "_")}`, "begin",
    "wwv_flow_imp.g_varchar2_table := wwv_flow_imp.empty_varchar2_table;");
  for (let i = 0, n = 1; i < hex.length; i += 400, n++) sql.push(`wwv_flow_imp.g_varchar2_table(${n}) := '${hex.slice(i, i + 400)}';`);
  sql.push("end;", "/", "begin",
    "wwv_flow_imp_shared.create_app_static_file(",
    ` p_id=>wwv_flow_imp.id(${makeId(published)})`,
    `,p_file_name=>${q(published)}`,
    `,p_mime_type=>${q(f.mime)}`,
    ",p_file_charset=>'utf-8'",
    ",p_file_content=>wwv_flow_imp.varchar2_to_blob(wwv_flow_imp.g_varchar2_table)",
    ");", "end;", "/");
}

sql.push("prompt --application/end_environment", "begin",
  "wwv_flow_imp.import_end(p_auto_install_sup_obj => nvl(wwv_flow_application_install.get_auto_install_sup_obj, false));",
  "commit;", "end;", "/", "set verify on feedback on define on", "prompt  ...done", "");

outputs.set(path.join(DIST, "apexlang", "static-files.snippet.apx"), staticEntries.join("\n"));
outputs.set(path.join(DIST, "apexlang", "application.snippet.apx"), [
  "    javaScript {",
  "        fileUrls: [",
  ...urls.js.map((u) => `            ${u}`),
  "        ]",
  "    }",
  "    css {",
  "        fileUrls: [",
  ...urls.css.map((u) => `            ${u}`),
  "        ]",
  "    }",
  ""
].join("\n"));
outputs.set(path.join(DIST, "legacy", `install_${FOLDER.replace(/-/g, "_")}.sql`), sql.join("\n"));
}

let stale = 0;
for (const [file, content] of outputs) {
  const buf = Buffer.isBuffer(content) ? content : Buffer.from(content);
  if (fs.existsSync(file) && fs.readFileSync(file).equals(buf)) continue;
  if (check) { console.error(`stale ${path.relative(SKILL_ROOT, file)}`); stale++; continue; }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, buf);
  console.log(`wrote ${path.relative(SKILL_ROOT, file)}`);
}
if (stale) { console.error("kit dist is stale: run node tools/build-kit.mjs"); process.exit(1); }
console.log(`ok    ${KITS.map((k) => k.title.toLowerCase()).join(", ")}`);
