#!/usr/bin/env node
// Validates and packages the Universal Theme styles in theme-styles/.
//
//   node tools/build-styles.mjs                 write dist/, READMEs and the catalog
//   node tools/build-styles.mjs --check         fail if anything is invalid or stale (CI)
//   node tools/build-styles.mjs --only <slug>   validate and build one style
//
// Per style (theme-styles/<slug>/dist/):
//   apexlang/shared-components/themes/universal-theme/styles/amc-<slug>.apx
//   apexlang/shared-components/static-files/amc-styles/amc-style-<slug>.css
//   apexlang/static-files.snippet.apx
//   legacy/amc_style_<slug>.sql                     APEX 23.1+ (theme style + static file)
// Pack: theme-styles/dist/legacy/install_amc_styles.sql, assets/styles.catalog.json

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  BASES, STYLE_FOLDER, apexlangPath, emitApexlang, legacyBody, legacyFooter, legacyHeader,
  listStyleDirs, loadStyle, styleId, validateStyle
} from "./lib/theme-styles.mjs";

const SKILL_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ROOT = path.join(SKILL_ROOT, "theme-styles");
const args = process.argv.slice(2);
const check = args.includes("--check");
const only = args.includes("--only") ? args[args.indexOf("--only") + 1] : null;

let dirs = listStyleDirs(ROOT);
if (only) dirs = dirs.filter((d) => path.basename(d) === only);
if (only && !dirs.length) { console.error(`no style folder theme-styles/${only}`); process.exit(1); }

const outputs = new Map();
const put = (f, c) => outputs.set(f, Buffer.isBuffer(c) ? c : Buffer.from(c));
let errorCount = 0;
const styles = [];

for (const dir of dirs) {
  let t;
  try { t = loadStyle(dir); } catch (e) { console.error(`error ${path.basename(dir)}: cannot load: ${e.message}`); errorCount++; continue; }
  const { errors, warnings, contrast } = validateStyle(t);
  warnings.forEach((w) => console.warn(`warn  ${w}`));
  errors.forEach((e) => console.error(`error ${e}`));
  if (errors.length) { errorCount += errors.length; continue; }
  t.contrast = contrast;
  styles.push(t);
  const dist = path.join(dir, "dist");
  put(path.join(dist, "apexlang", apexlangPath(t)), emitApexlang(t));
  put(path.join(dist, "apexlang", "shared-components", "static-files", STYLE_FOLDER, t.fileName), t.css);
  put(path.join(dist, "apexlang", "static-files.snippet.apx"), [`file "${STYLE_FOLDER}/${t.fileName}" (`, "    mimeType: text/css", "    charSet: utf-8", ")", ""].join("\n"));
  put(path.join(dist, "legacy", `amc_style_${t.slug.replace(/-/g, "_")}.sql`),
    [...legacyHeader(`Theme Style "${t.spec.name}"`), ...legacyBody(t), ...legacyFooter()].join("\n"));
  put(path.join(dir, "README.md"), readme(t));
}

if (!only && styles.length) {
  put(path.join(ROOT, "dist", "legacy", "install_amc_styles.sql"),
    [...legacyHeader(`all ${styles.length} theme styles`), ...styles.flatMap(legacyBody), ...legacyFooter()].join("\n"));
  put(path.join(SKILL_ROOT, "assets", "styles.catalog.json"), JSON.stringify({
    generatedBy: "tools/build-styles.mjs",
    styles: styles.map((t) => ({
      slug: t.slug, name: t.spec.name, staticId: t.spec.staticId, apexlangId: styleId(t), base: t.spec.base,
      scheme: t.spec.scheme, version: t.spec.version, description: t.spec.description, keywords: t.spec.keywords || [],
      contrast: t.contrast.map((r) => ({ scheme: r.scheme, pair: `${r.f} on ${r.b}`, ratio: r.ratio, min: r.min })),
      apexlang: path.posix.join("theme-styles", t.slug, "dist", "apexlang"),
      legacySql: path.posix.join("theme-styles", t.slug, "dist", "legacy", `amc_style_${t.slug.replace(/-/g, "_")}.sql`)
    }))
  }, null, 2) + "\n");
}

if (errorCount) { console.error(`${errorCount} error(s)`); process.exit(1); }
let stale = 0;
for (const [file, buf] of outputs) {
  if (fs.existsSync(file) && fs.readFileSync(file).equals(buf)) continue;
  if (check) { console.error(`stale ${path.relative(SKILL_ROOT, file)}`); stale++; continue; }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, buf);
}
if (stale) { console.error("theme style output is stale: run node tools/build-styles.mjs"); process.exit(1); }
console.log(`ok    ${styles.length} theme style(s)`);

function readme(t) {
  const s = t.spec;
  return [
    `# ${s.name}`,
    "",
    "<!-- Generated by tools/build-styles.mjs from style.json. Do not edit by hand. -->",
    "",
    `**Universal Theme style** · ${s.scheme} · built on ${s.base} · APEX 23.1+ · v${s.version}`,
    "",
    s.description,
    "",
    "## Install",
    "",
    `- **APEX 23.1 to 25.x:** Shared Components > Export/Import > Import \`dist/legacy/amc_style_${t.slug.replace(/-/g, "_")}.sql\``,
    `  (Component Export) into an app on Universal Theme. It adds the style to Theme 42 and uploads`,
    `  \`${STYLE_FOLDER}/${t.fileName}\` as a Static Application File. Then pick it in Theme Roller or`,
    "  Shared Components > Themes > Universal Theme > Styles (Set as Current), or let users pick it when",
    "  Customization is enabled.",
    `- **APEX 26.1+ (APEXlang):** copy \`dist/apexlang/${apexlangPath(t)}\` and the static file, merge`,
    "  `dist/apexlang/static-files.snippet.apx`, and set `style.currentThemeStyle` in `theme.apx` to",
    `  \`@${styleId(t)}\` if it should be the default. Then run the apexlang gates.`,
    "",
    "## Contrast (WCAG, computed by the build)",
    "",
    "| Scheme | Pair | Ratio | Minimum |",
    "|---|---|---:|---:|",
    ...t.contrast.map((r) => `| ${r.scheme} | ${r.f} on ${r.b} | ${r.ratio ?? "n/a"} | ${r.min} |`),
    "",
    s.helpText,
    "",
    "Status: validated offline (contrast, rules, apexlang formatter) and previewed on a Universal Theme mock page.",
    "Not yet applied to a live APEX instance.",
    ""
  ].join("\n");
}
