// Generates components/<slug>/README.md from component.json so the settings
// reference can never drift from the plug-in definition.

import fs from "node:fs";
import path from "node:path";

export function emitReadme(unit) {
  const { component: c, slug, dir } = unit;
  const examplesDir = path.join(dir, "examples");
  const examples = fs.existsSync(examplesDir)
    ? fs.readdirSync(examplesDir).filter((f) => f.endsWith(".md")).sort()
    : [];
  const pluginRef = `plugin/${c.apexlangName}`;
  const modes = c.templateComponent
    ? c.templateComponent.availableAs.map((m) => (m === "partial" ? "partial (single / report column)" : "report (multiple rows)")).join(", ")
    : "page item";

  const rows = [...c.attributes]
    .sort((a, b) => a.sequence - b.sequence)
    .map((a) => {
      const values = a.entries?.length ? a.entries.map((e) => `\`${e.name}\``).join(", ") : "";
      const def = a.default !== undefined && a.default !== null ? `\`${a.default}\`` : "";
      return `| \`${a.apexlangName}\` | ${a.name} | ${a.type}${values ? ` (${values})` : ""} | ${a.required ? "yes" : ""} | ${def} | ${a.helpText.replace(/\|/g, "\\|")} |`;
    });

  const unverified = c.item?.apexlangUnverifiedTokens?.length
    ? `\n> **APEXlang verification required.** These plug-in definition tokens are not yet confirmed by compiler truth: ${c.item.apexlangUnverifiedTokens.map((t) => `\`${t}\``).join(", ")}. Run \`node tools/query-valid-props.mjs --component plugin --when type=ITEM\` in the apexlang skill, fix \`tools/lib/tokens.mjs\` or \`component.json\` if needed, and rebuild before importing.\n`
    : "";

  return `<!-- Generated by tools/build.mjs from component.json. Edit component.json, then rebuild. -->
# ${c.name}

${c.description}

| | |
|---|---|
| Plug-in type | ${c.pluginType} |
| Static ID | \`${c.staticId}\` |
| APEXlang reference | \`type: ${pluginRef}\` |
| Modes | ${modes} |
| Minimum APEX | ${c.minApexVersion} (APEXlang import: 26.1+) |
| Version | ${c.version} |
${c.source ? `| Based on | [${c.source.author || c.source.url}](${c.source.url}) (${c.source.license}) |\n` : ""}${unverified}
${c.helpText}

## Settings

| APEXlang setting | Builder label | Type | Required | Default | Notes |
|---|---|---|---|---|---|
${rows.join("\n")}

## Install

- **APEX 26.1+ with APEXlang:** copy \`dist/apexlang/shared-components/plugins/${slug}/\` into your app's \`shared-components/plugins/\`, then run the apexlang skill's format, compiler-truth and runtime validate gates.
- **APEX 23.1 to 25.x (or any version, via App Builder):** import \`dist/legacy/${c.staticId.toLowerCase()}.sql\` from Shared Components > Plug-ins > Import.

## Examples

${examples.length ? examples.map((e) => `- [${e.replace(/\.apx\.md$|\.md$/, "")}](examples/${e})`).join("\n") : "- none yet"}
`;
}
